// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	packet "github.com/vx-labs/mqtt-protocol/packet"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DistributeMessageRequest struct {
	Message                 *packet.Publish `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	ResolveRemoteRecipients bool            `protobuf:"varint,2,opt,name=ResolveRemoteRecipients,proto3" json:"ResolveRemoteRecipients,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}        `json:"-"`
	XXX_unrecognized        []byte          `json:"-"`
	XXX_sizecache           int32           `json:"-"`
}

func (m *DistributeMessageRequest) Reset()         { *m = DistributeMessageRequest{} }
func (m *DistributeMessageRequest) String() string { return proto.CompactTextString(m) }
func (*DistributeMessageRequest) ProtoMessage()    {}
func (*DistributeMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *DistributeMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistributeMessageRequest.Unmarshal(m, b)
}
func (m *DistributeMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistributeMessageRequest.Marshal(b, m, deterministic)
}
func (m *DistributeMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistributeMessageRequest.Merge(m, src)
}
func (m *DistributeMessageRequest) XXX_Size() int {
	return xxx_messageInfo_DistributeMessageRequest.Size(m)
}
func (m *DistributeMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DistributeMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DistributeMessageRequest proto.InternalMessageInfo

func (m *DistributeMessageRequest) GetMessage() *packet.Publish {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *DistributeMessageRequest) GetResolveRemoteRecipients() bool {
	if m != nil {
		return m.ResolveRemoteRecipients
	}
	return false
}

type DistributeMessageResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DistributeMessageResponse) Reset()         { *m = DistributeMessageResponse{} }
func (m *DistributeMessageResponse) String() string { return proto.CompactTextString(m) }
func (*DistributeMessageResponse) ProtoMessage()    {}
func (*DistributeMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *DistributeMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistributeMessageResponse.Unmarshal(m, b)
}
func (m *DistributeMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistributeMessageResponse.Marshal(b, m, deterministic)
}
func (m *DistributeMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistributeMessageResponse.Merge(m, src)
}
func (m *DistributeMessageResponse) XXX_Size() int {
	return xxx_messageInfo_DistributeMessageResponse.Size(m)
}
func (m *DistributeMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DistributeMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DistributeMessageResponse proto.InternalMessageInfo

type SessionMetadatas struct {
	SessionID            string          `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	ClientID             string          `protobuf:"bytes,2,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	ConnectedAt          int64           `protobuf:"varint,3,opt,name=ConnectedAt,proto3" json:"ConnectedAt,omitempty"`
	Peer                 uint64          `protobuf:"varint,4,opt,name=Peer,proto3" json:"Peer,omitempty"`
	LWT                  *packet.Publish `protobuf:"bytes,5,opt,name=LWT,proto3" json:"LWT,omitempty"`
	MountPoint           string          `protobuf:"bytes,6,opt,name=MountPoint,proto3" json:"MountPoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SessionMetadatas) Reset()         { *m = SessionMetadatas{} }
func (m *SessionMetadatas) String() string { return proto.CompactTextString(m) }
func (*SessionMetadatas) ProtoMessage()    {}
func (*SessionMetadatas) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *SessionMetadatas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionMetadatas.Unmarshal(m, b)
}
func (m *SessionMetadatas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionMetadatas.Marshal(b, m, deterministic)
}
func (m *SessionMetadatas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionMetadatas.Merge(m, src)
}
func (m *SessionMetadatas) XXX_Size() int {
	return xxx_messageInfo_SessionMetadatas.Size(m)
}
func (m *SessionMetadatas) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionMetadatas.DiscardUnknown(m)
}

var xxx_messageInfo_SessionMetadatas proto.InternalMessageInfo

func (m *SessionMetadatas) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *SessionMetadatas) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *SessionMetadatas) GetConnectedAt() int64 {
	if m != nil {
		return m.ConnectedAt
	}
	return 0
}

func (m *SessionMetadatas) GetPeer() uint64 {
	if m != nil {
		return m.Peer
	}
	return 0
}

func (m *SessionMetadatas) GetLWT() *packet.Publish {
	if m != nil {
		return m.LWT
	}
	return nil
}

func (m *SessionMetadatas) GetMountPoint() string {
	if m != nil {
		return m.MountPoint
	}
	return ""
}

type ListSessionMetadatasRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSessionMetadatasRequest) Reset()         { *m = ListSessionMetadatasRequest{} }
func (m *ListSessionMetadatasRequest) String() string { return proto.CompactTextString(m) }
func (*ListSessionMetadatasRequest) ProtoMessage()    {}
func (*ListSessionMetadatasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *ListSessionMetadatasRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSessionMetadatasRequest.Unmarshal(m, b)
}
func (m *ListSessionMetadatasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSessionMetadatasRequest.Marshal(b, m, deterministic)
}
func (m *ListSessionMetadatasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSessionMetadatasRequest.Merge(m, src)
}
func (m *ListSessionMetadatasRequest) XXX_Size() int {
	return xxx_messageInfo_ListSessionMetadatasRequest.Size(m)
}
func (m *ListSessionMetadatasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSessionMetadatasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSessionMetadatasRequest proto.InternalMessageInfo

type ListSessionMetadatasResponse struct {
	SessionMetadatasList []*SessionMetadatas `protobuf:"bytes,1,rep,name=SessionMetadatasList,proto3" json:"SessionMetadatasList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ListSessionMetadatasResponse) Reset()         { *m = ListSessionMetadatasResponse{} }
func (m *ListSessionMetadatasResponse) String() string { return proto.CompactTextString(m) }
func (*ListSessionMetadatasResponse) ProtoMessage()    {}
func (*ListSessionMetadatasResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *ListSessionMetadatasResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSessionMetadatasResponse.Unmarshal(m, b)
}
func (m *ListSessionMetadatasResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSessionMetadatasResponse.Marshal(b, m, deterministic)
}
func (m *ListSessionMetadatasResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSessionMetadatasResponse.Merge(m, src)
}
func (m *ListSessionMetadatasResponse) XXX_Size() int {
	return xxx_messageInfo_ListSessionMetadatasResponse.Size(m)
}
func (m *ListSessionMetadatasResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSessionMetadatasResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSessionMetadatasResponse proto.InternalMessageInfo

func (m *ListSessionMetadatasResponse) GetSessionMetadatasList() []*SessionMetadatas {
	if m != nil {
		return m.SessionMetadatasList
	}
	return nil
}

type CreateSubscriptionRequest struct {
	SessionID            string   `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	Peer                 uint64   `protobuf:"varint,2,opt,name=Peer,proto3" json:"Peer,omitempty"`
	Pattern              []byte   `protobuf:"bytes,3,opt,name=Pattern,proto3" json:"Pattern,omitempty"`
	QoS                  int32    `protobuf:"varint,4,opt,name=QoS,proto3" json:"QoS,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSubscriptionRequest) Reset()         { *m = CreateSubscriptionRequest{} }
func (m *CreateSubscriptionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSubscriptionRequest) ProtoMessage()    {}
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *CreateSubscriptionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSubscriptionRequest.Unmarshal(m, b)
}
func (m *CreateSubscriptionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSubscriptionRequest.Marshal(b, m, deterministic)
}
func (m *CreateSubscriptionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSubscriptionRequest.Merge(m, src)
}
func (m *CreateSubscriptionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSubscriptionRequest.Size(m)
}
func (m *CreateSubscriptionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSubscriptionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSubscriptionRequest proto.InternalMessageInfo

func (m *CreateSubscriptionRequest) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *CreateSubscriptionRequest) GetPeer() uint64 {
	if m != nil {
		return m.Peer
	}
	return 0
}

func (m *CreateSubscriptionRequest) GetPattern() []byte {
	if m != nil {
		return m.Pattern
	}
	return nil
}

func (m *CreateSubscriptionRequest) GetQoS() int32 {
	if m != nil {
		return m.QoS
	}
	return 0
}

type CreateSubscriptionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSubscriptionResponse) Reset()         { *m = CreateSubscriptionResponse{} }
func (m *CreateSubscriptionResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSubscriptionResponse) ProtoMessage()    {}
func (*CreateSubscriptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *CreateSubscriptionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSubscriptionResponse.Unmarshal(m, b)
}
func (m *CreateSubscriptionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSubscriptionResponse.Marshal(b, m, deterministic)
}
func (m *CreateSubscriptionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSubscriptionResponse.Merge(m, src)
}
func (m *CreateSubscriptionResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSubscriptionResponse.Size(m)
}
func (m *CreateSubscriptionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSubscriptionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSubscriptionResponse proto.InternalMessageInfo

type DeleteSubscriptionRequest struct {
	SessionID            string   `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	Peer                 uint64   `protobuf:"varint,2,opt,name=Peer,proto3" json:"Peer,omitempty"`
	Pattern              []byte   `protobuf:"bytes,3,opt,name=Pattern,proto3" json:"Pattern,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSubscriptionRequest) Reset()         { *m = DeleteSubscriptionRequest{} }
func (m *DeleteSubscriptionRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSubscriptionRequest) ProtoMessage()    {}
func (*DeleteSubscriptionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *DeleteSubscriptionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSubscriptionRequest.Unmarshal(m, b)
}
func (m *DeleteSubscriptionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSubscriptionRequest.Marshal(b, m, deterministic)
}
func (m *DeleteSubscriptionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSubscriptionRequest.Merge(m, src)
}
func (m *DeleteSubscriptionRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSubscriptionRequest.Size(m)
}
func (m *DeleteSubscriptionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSubscriptionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSubscriptionRequest proto.InternalMessageInfo

func (m *DeleteSubscriptionRequest) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *DeleteSubscriptionRequest) GetPeer() uint64 {
	if m != nil {
		return m.Peer
	}
	return 0
}

func (m *DeleteSubscriptionRequest) GetPattern() []byte {
	if m != nil {
		return m.Pattern
	}
	return nil
}

type DeleteSubscriptionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSubscriptionResponse) Reset()         { *m = DeleteSubscriptionResponse{} }
func (m *DeleteSubscriptionResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteSubscriptionResponse) ProtoMessage()    {}
func (*DeleteSubscriptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *DeleteSubscriptionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSubscriptionResponse.Unmarshal(m, b)
}
func (m *DeleteSubscriptionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSubscriptionResponse.Marshal(b, m, deterministic)
}
func (m *DeleteSubscriptionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSubscriptionResponse.Merge(m, src)
}
func (m *DeleteSubscriptionResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteSubscriptionResponse.Size(m)
}
func (m *DeleteSubscriptionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSubscriptionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSubscriptionResponse proto.InternalMessageInfo

type ListSubscriptionsResponse struct {
	Subscriptions        []*CreateSubscriptionRequest `protobuf:"bytes,1,rep,name=Subscriptions,proto3" json:"Subscriptions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ListSubscriptionsResponse) Reset()         { *m = ListSubscriptionsResponse{} }
func (m *ListSubscriptionsResponse) String() string { return proto.CompactTextString(m) }
func (*ListSubscriptionsResponse) ProtoMessage()    {}
func (*ListSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *ListSubscriptionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSubscriptionsResponse.Unmarshal(m, b)
}
func (m *ListSubscriptionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSubscriptionsResponse.Marshal(b, m, deterministic)
}
func (m *ListSubscriptionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSubscriptionsResponse.Merge(m, src)
}
func (m *ListSubscriptionsResponse) XXX_Size() int {
	return xxx_messageInfo_ListSubscriptionsResponse.Size(m)
}
func (m *ListSubscriptionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSubscriptionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSubscriptionsResponse proto.InternalMessageInfo

func (m *ListSubscriptionsResponse) GetSubscriptions() []*CreateSubscriptionRequest {
	if m != nil {
		return m.Subscriptions
	}
	return nil
}

type ListSubscriptionsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSubscriptionsRequest) Reset()         { *m = ListSubscriptionsRequest{} }
func (m *ListSubscriptionsRequest) String() string { return proto.CompactTextString(m) }
func (*ListSubscriptionsRequest) ProtoMessage()    {}
func (*ListSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *ListSubscriptionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSubscriptionsRequest.Unmarshal(m, b)
}
func (m *ListSubscriptionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSubscriptionsRequest.Marshal(b, m, deterministic)
}
func (m *ListSubscriptionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSubscriptionsRequest.Merge(m, src)
}
func (m *ListSubscriptionsRequest) XXX_Size() int {
	return xxx_messageInfo_ListSubscriptionsRequest.Size(m)
}
func (m *ListSubscriptionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSubscriptionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSubscriptionsRequest proto.InternalMessageInfo

type ShutdownRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutdownRequest) Reset()         { *m = ShutdownRequest{} }
func (m *ShutdownRequest) String() string { return proto.CompactTextString(m) }
func (*ShutdownRequest) ProtoMessage()    {}
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11}
}

func (m *ShutdownRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownRequest.Unmarshal(m, b)
}
func (m *ShutdownRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownRequest.Marshal(b, m, deterministic)
}
func (m *ShutdownRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownRequest.Merge(m, src)
}
func (m *ShutdownRequest) XXX_Size() int {
	return xxx_messageInfo_ShutdownRequest.Size(m)
}
func (m *ShutdownRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownRequest proto.InternalMessageInfo

type ShutdownResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutdownResponse) Reset()         { *m = ShutdownResponse{} }
func (m *ShutdownResponse) String() string { return proto.CompactTextString(m) }
func (*ShutdownResponse) ProtoMessage()    {}
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{12}
}

func (m *ShutdownResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownResponse.Unmarshal(m, b)
}
func (m *ShutdownResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownResponse.Marshal(b, m, deterministic)
}
func (m *ShutdownResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownResponse.Merge(m, src)
}
func (m *ShutdownResponse) XXX_Size() int {
	return xxx_messageInfo_ShutdownResponse.Size(m)
}
func (m *ShutdownResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*DistributeMessageRequest)(nil), "api.DistributeMessageRequest")
	proto.RegisterType((*DistributeMessageResponse)(nil), "api.DistributeMessageResponse")
	proto.RegisterType((*SessionMetadatas)(nil), "api.SessionMetadatas")
	proto.RegisterType((*ListSessionMetadatasRequest)(nil), "api.ListSessionMetadatasRequest")
	proto.RegisterType((*ListSessionMetadatasResponse)(nil), "api.ListSessionMetadatasResponse")
	proto.RegisterType((*CreateSubscriptionRequest)(nil), "api.CreateSubscriptionRequest")
	proto.RegisterType((*CreateSubscriptionResponse)(nil), "api.CreateSubscriptionResponse")
	proto.RegisterType((*DeleteSubscriptionRequest)(nil), "api.DeleteSubscriptionRequest")
	proto.RegisterType((*DeleteSubscriptionResponse)(nil), "api.DeleteSubscriptionResponse")
	proto.RegisterType((*ListSubscriptionsResponse)(nil), "api.ListSubscriptionsResponse")
	proto.RegisterType((*ListSubscriptionsRequest)(nil), "api.ListSubscriptionsRequest")
	proto.RegisterType((*ShutdownRequest)(nil), "api.ShutdownRequest")
	proto.RegisterType((*ShutdownResponse)(nil), "api.ShutdownResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 573 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0x4b, 0x6f, 0xd3, 0x40,
	0x10, 0xc7, 0xeb, 0x3a, 0x7d, 0x64, 0x0a, 0x6a, 0x3b, 0x6a, 0x85, 0xe3, 0xb6, 0xc1, 0xf5, 0x29,
	0x1c, 0x9a, 0xa0, 0x70, 0x81, 0x63, 0x95, 0x5c, 0x22, 0x35, 0x28, 0xdd, 0x44, 0xea, 0x89, 0x83,
	0xed, 0x8c, 0x92, 0x15, 0x8e, 0xd7, 0xf5, 0xae, 0x0b, 0x9c, 0xf8, 0x70, 0x88, 0xef, 0x85, 0xfc,
	0x22, 0x2f, 0x3b, 0x9c, 0xb8, 0x79, 0xe7, 0xbf, 0xf3, 0xf0, 0xef, 0xbf, 0xbb, 0x50, 0x77, 0x42,
	0xde, 0x0e, 0x23, 0xa1, 0x04, 0xea, 0x4e, 0xc8, 0xcd, 0xf7, 0x33, 0xae, 0xe6, 0xb1, 0xdb, 0xf6,
	0xc4, 0xa2, 0xf3, 0xf2, 0xfd, 0xce, 0x77, 0x5c, 0xd9, 0x59, 0x3c, 0x2b, 0x75, 0x97, 0xee, 0xf1,
	0x84, 0xdf, 0x09, 0x1d, 0xef, 0x2b, 0xa9, 0x4e, 0xe8, 0x66, 0x69, 0xf6, 0x4f, 0x30, 0xfa, 0x5c,
	0xaa, 0x88, 0xbb, 0xb1, 0xa2, 0x21, 0x49, 0xe9, 0xcc, 0x88, 0xd1, 0x73, 0x4c, 0x52, 0xe1, 0x3b,
	0x38, 0xca, 0x23, 0x86, 0x66, 0x69, 0xad, 0x93, 0xee, 0x69, 0x3b, 0x4b, 0x6f, 0x8f, 0x62, 0xd7,
	0xe7, 0x72, 0xce, 0x0a, 0x1d, 0x3f, 0xc2, 0x1b, 0x46, 0x52, 0xf8, 0x2f, 0xc4, 0x68, 0x21, 0x14,
	0x31, 0xf2, 0x78, 0xc8, 0x29, 0x50, 0xd2, 0xd8, 0xb7, 0xb4, 0xd6, 0x31, 0xab, 0x92, 0xed, 0x2b,
	0x68, 0x94, 0x0c, 0x20, 0x43, 0x11, 0x48, 0xb2, 0x7f, 0x6b, 0x70, 0x36, 0x26, 0x29, 0xb9, 0x08,
	0x86, 0xa4, 0x9c, 0xa9, 0xa3, 0x1c, 0x89, 0xd7, 0x50, 0xcf, 0x63, 0x83, 0x7e, 0x3a, 0x58, 0x9d,
	0x2d, 0x03, 0x68, 0xc2, 0x71, 0xcf, 0x4f, 0x4a, 0x0f, 0xfa, 0x69, 0xeb, 0x3a, 0xfb, 0xbb, 0x46,
	0x0b, 0x4e, 0x7a, 0x22, 0x08, 0xc8, 0x53, 0x34, 0xbd, 0x57, 0x86, 0x6e, 0x69, 0x2d, 0x9d, 0xad,
	0x86, 0x10, 0xa1, 0x36, 0x22, 0x8a, 0x8c, 0x9a, 0xa5, 0xb5, 0x6a, 0x2c, 0xfd, 0xc6, 0x5b, 0xd0,
	0x1f, 0x9e, 0x26, 0xc6, 0x41, 0x39, 0x82, 0x44, 0xc3, 0x26, 0xc0, 0x50, 0xc4, 0x81, 0x1a, 0x09,
	0x1e, 0x28, 0xe3, 0x30, 0x6d, 0xbb, 0x12, 0xb1, 0x6f, 0xe0, 0xea, 0x81, 0x4b, 0xb5, 0xf9, 0x2b,
	0x39, 0x68, 0x9b, 0xc3, 0x75, 0xb9, 0x9c, 0x61, 0xc0, 0x01, 0x5c, 0x6c, 0x6a, 0xc9, 0x7e, 0x43,
	0xb3, 0xf4, 0xd6, 0x49, 0xf7, 0xb2, 0x9d, 0x9c, 0x82, 0xad, 0xe4, 0xd2, 0x14, 0xfb, 0x07, 0x34,
	0x7a, 0x11, 0x39, 0x8a, 0xc6, 0xb1, 0x2b, 0xbd, 0x88, 0x87, 0x8a, 0x8b, 0xa0, 0x30, 0x7c, 0x37,
	0xd9, 0x82, 0xcd, 0xfe, 0x0a, 0x1b, 0x03, 0x8e, 0x46, 0x8e, 0x52, 0x14, 0x05, 0x29, 0xcd, 0x57,
	0xac, 0x58, 0xe2, 0x19, 0xe8, 0x8f, 0x62, 0x9c, 0x82, 0x3c, 0x60, 0xc9, 0xa7, 0x7d, 0x0d, 0x66,
	0x59, 0xeb, 0xdc, 0xea, 0x19, 0x34, 0xfa, 0xe4, 0xd3, 0x7f, 0x1f, 0x2c, 0x19, 0xa3, 0xac, 0x51,
	0x3e, 0x86, 0x03, 0x8d, 0xd4, 0x8a, 0x15, 0x6d, 0xe9, 0x43, 0x1f, 0x5e, 0xaf, 0x09, 0xb9, 0x01,
	0xcd, 0xd4, 0x80, 0x4a, 0xac, 0x6c, 0x3d, 0xc9, 0x36, 0xc1, 0x28, 0x69, 0x91, 0x9d, 0x84, 0x73,
	0x38, 0x1d, 0xcf, 0x63, 0x35, 0x15, 0xdf, 0x8a, 0x6c, 0x1b, 0xe1, 0x6c, 0x19, 0xca, 0x06, 0xe9,
	0xfe, 0xd2, 0xa1, 0x36, 0x7c, 0x9c, 0x4c, 0x70, 0x02, 0xe7, 0x5b, 0xb5, 0xf0, 0x26, 0x9d, 0xa7,
	0xaa, 0x87, 0xd9, 0xac, 0x92, 0x73, 0x04, 0x7b, 0xf8, 0x04, 0xb8, 0x8d, 0x08, 0xb3, 0xbc, 0x4a,
	0x93, 0xcc, 0xb7, 0x95, 0xfa, 0x6a, 0xe1, 0x6d, 0x4c, 0xf8, 0x0f, 0x7e, 0x79, 0xe1, 0x1d, 0x67,
	0x67, 0x2f, 0xe1, 0xb0, 0xf5, 0x8a, 0xe4, 0x1c, 0xaa, 0x9e, 0xb7, 0x9c, 0x43, 0xf5, 0xe3, 0xb3,
	0x87, 0x5f, 0xe0, 0xa2, 0xec, 0x5e, 0xa2, 0xb5, 0x24, 0x58, 0x7e, 0xa3, 0xcd, 0xdb, 0x1d, 0x3b,
	0x8a, 0xf2, 0xdd, 0x7b, 0xa8, 0x7d, 0x16, 0x53, 0xc2, 0x4f, 0x70, 0x5c, 0x38, 0x8c, 0x17, 0xd9,
	0x65, 0x5e, 0x3f, 0x03, 0xe6, 0xe5, 0x46, 0xb4, 0x28, 0xe1, 0x1e, 0xa6, 0xaf, 0xf8, 0x87, 0x3f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x80, 0xde, 0x4a, 0xe1, 0x09, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MQTTClient is the client API for MQTT service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MQTTClient interface {
	ListSubscriptions(ctx context.Context, in *ListSubscriptionsRequest, opts ...grpc.CallOption) (*ListSubscriptionsResponse, error)
	DeleteSubscription(ctx context.Context, in *DeleteSubscriptionRequest, opts ...grpc.CallOption) (*DeleteSubscriptionResponse, error)
	CreateSubscription(ctx context.Context, in *CreateSubscriptionRequest, opts ...grpc.CallOption) (*CreateSubscriptionResponse, error)
	DistributeMessage(ctx context.Context, in *DistributeMessageRequest, opts ...grpc.CallOption) (*DistributeMessageResponse, error)
	ListSessionMetadatas(ctx context.Context, in *ListSessionMetadatasRequest, opts ...grpc.CallOption) (*ListSessionMetadatasResponse, error)
}

type mQTTClient struct {
	cc *grpc.ClientConn
}

func NewMQTTClient(cc *grpc.ClientConn) MQTTClient {
	return &mQTTClient{cc}
}

func (c *mQTTClient) ListSubscriptions(ctx context.Context, in *ListSubscriptionsRequest, opts ...grpc.CallOption) (*ListSubscriptionsResponse, error) {
	out := new(ListSubscriptionsResponse)
	err := c.cc.Invoke(ctx, "/api.MQTT/ListSubscriptions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mQTTClient) DeleteSubscription(ctx context.Context, in *DeleteSubscriptionRequest, opts ...grpc.CallOption) (*DeleteSubscriptionResponse, error) {
	out := new(DeleteSubscriptionResponse)
	err := c.cc.Invoke(ctx, "/api.MQTT/DeleteSubscription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mQTTClient) CreateSubscription(ctx context.Context, in *CreateSubscriptionRequest, opts ...grpc.CallOption) (*CreateSubscriptionResponse, error) {
	out := new(CreateSubscriptionResponse)
	err := c.cc.Invoke(ctx, "/api.MQTT/CreateSubscription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mQTTClient) DistributeMessage(ctx context.Context, in *DistributeMessageRequest, opts ...grpc.CallOption) (*DistributeMessageResponse, error) {
	out := new(DistributeMessageResponse)
	err := c.cc.Invoke(ctx, "/api.MQTT/DistributeMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mQTTClient) ListSessionMetadatas(ctx context.Context, in *ListSessionMetadatasRequest, opts ...grpc.CallOption) (*ListSessionMetadatasResponse, error) {
	out := new(ListSessionMetadatasResponse)
	err := c.cc.Invoke(ctx, "/api.MQTT/ListSessionMetadatas", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MQTTServer is the server API for MQTT service.
type MQTTServer interface {
	ListSubscriptions(context.Context, *ListSubscriptionsRequest) (*ListSubscriptionsResponse, error)
	DeleteSubscription(context.Context, *DeleteSubscriptionRequest) (*DeleteSubscriptionResponse, error)
	CreateSubscription(context.Context, *CreateSubscriptionRequest) (*CreateSubscriptionResponse, error)
	DistributeMessage(context.Context, *DistributeMessageRequest) (*DistributeMessageResponse, error)
	ListSessionMetadatas(context.Context, *ListSessionMetadatasRequest) (*ListSessionMetadatasResponse, error)
}

// UnimplementedMQTTServer can be embedded to have forward compatible implementations.
type UnimplementedMQTTServer struct {
}

func (*UnimplementedMQTTServer) ListSubscriptions(ctx context.Context, req *ListSubscriptionsRequest) (*ListSubscriptionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSubscriptions not implemented")
}
func (*UnimplementedMQTTServer) DeleteSubscription(ctx context.Context, req *DeleteSubscriptionRequest) (*DeleteSubscriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSubscription not implemented")
}
func (*UnimplementedMQTTServer) CreateSubscription(ctx context.Context, req *CreateSubscriptionRequest) (*CreateSubscriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSubscription not implemented")
}
func (*UnimplementedMQTTServer) DistributeMessage(ctx context.Context, req *DistributeMessageRequest) (*DistributeMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DistributeMessage not implemented")
}
func (*UnimplementedMQTTServer) ListSessionMetadatas(ctx context.Context, req *ListSessionMetadatasRequest) (*ListSessionMetadatasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSessionMetadatas not implemented")
}

func RegisterMQTTServer(s *grpc.Server, srv MQTTServer) {
	s.RegisterService(&_MQTT_serviceDesc, srv)
}

func _MQTT_ListSubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSubscriptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MQTTServer).ListSubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MQTT/ListSubscriptions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MQTTServer).ListSubscriptions(ctx, req.(*ListSubscriptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MQTT_DeleteSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MQTTServer).DeleteSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MQTT/DeleteSubscription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MQTTServer).DeleteSubscription(ctx, req.(*DeleteSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MQTT_CreateSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MQTTServer).CreateSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MQTT/CreateSubscription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MQTTServer).CreateSubscription(ctx, req.(*CreateSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MQTT_DistributeMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DistributeMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MQTTServer).DistributeMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MQTT/DistributeMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MQTTServer).DistributeMessage(ctx, req.(*DistributeMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MQTT_ListSessionMetadatas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionMetadatasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MQTTServer).ListSessionMetadatas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MQTT/ListSessionMetadatas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MQTTServer).ListSessionMetadatas(ctx, req.(*ListSessionMetadatasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MQTT_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.MQTT",
	HandlerType: (*MQTTServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSubscriptions",
			Handler:    _MQTT_ListSubscriptions_Handler,
		},
		{
			MethodName: "DeleteSubscription",
			Handler:    _MQTT_DeleteSubscription_Handler,
		},
		{
			MethodName: "CreateSubscription",
			Handler:    _MQTT_CreateSubscription_Handler,
		},
		{
			MethodName: "DistributeMessage",
			Handler:    _MQTT_DistributeMessage_Handler,
		},
		{
			MethodName: "ListSessionMetadatas",
			Handler:    _MQTT_ListSessionMetadatas_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

// NodeClient is the client API for Node service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodeClient interface {
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
}

type nodeClient struct {
	cc *grpc.ClientConn
}

func NewNodeClient(cc *grpc.ClientConn) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, "/api.Node/Shutdown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServer is the server API for Node service.
type NodeServer interface {
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
}

// UnimplementedNodeServer can be embedded to have forward compatible implementations.
type UnimplementedNodeServer struct {
}

func (*UnimplementedNodeServer) Shutdown(ctx context.Context, req *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}

func RegisterNodeServer(s *grpc.Server, srv NodeServer) {
	s.RegisterService(&_Node_serviceDesc, srv)
}

func _Node_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Node/Shutdown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Node_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Shutdown",
			Handler:    _Node_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
