// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	packet "github.com/vx-labs/mqtt-protocol/packet"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RetainedMessage struct {
	Publish              *packet.Publish `protobuf:"bytes,1,opt,name=Publish,proto3" json:"Publish,omitempty"`
	LastAdded            int64           `protobuf:"varint,2,opt,name=LastAdded,proto3" json:"LastAdded,omitempty"`
	LastDeleted          int64           `protobuf:"varint,3,opt,name=LastDeleted,proto3" json:"LastDeleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RetainedMessage) Reset()         { *m = RetainedMessage{} }
func (m *RetainedMessage) String() string { return proto.CompactTextString(m) }
func (*RetainedMessage) ProtoMessage()    {}
func (*RetainedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *RetainedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetainedMessage.Unmarshal(m, b)
}
func (m *RetainedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetainedMessage.Marshal(b, m, deterministic)
}
func (m *RetainedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetainedMessage.Merge(m, src)
}
func (m *RetainedMessage) XXX_Size() int {
	return xxx_messageInfo_RetainedMessage.Size(m)
}
func (m *RetainedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RetainedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RetainedMessage proto.InternalMessageInfo

func (m *RetainedMessage) GetPublish() *packet.Publish {
	if m != nil {
		return m.Publish
	}
	return nil
}

func (m *RetainedMessage) GetLastAdded() int64 {
	if m != nil {
		return m.LastAdded
	}
	return 0
}

func (m *RetainedMessage) GetLastDeleted() int64 {
	if m != nil {
		return m.LastDeleted
	}
	return 0
}

type SessionMetadatas struct {
	SessionID            string          `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	ClientID             string          `protobuf:"bytes,2,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	ConnectedAt          int64           `protobuf:"varint,3,opt,name=ConnectedAt,proto3" json:"ConnectedAt,omitempty"`
	Peer                 uint64          `protobuf:"varint,4,opt,name=Peer,proto3" json:"Peer,omitempty"`
	LWT                  *packet.Publish `protobuf:"bytes,5,opt,name=LWT,proto3" json:"LWT,omitempty"`
	MountPoint           string          `protobuf:"bytes,6,opt,name=MountPoint,proto3" json:"MountPoint,omitempty"`
	LastAdded            int64           `protobuf:"varint,7,opt,name=LastAdded,proto3" json:"LastAdded,omitempty"`
	LastDeleted          int64           `protobuf:"varint,8,opt,name=LastDeleted,proto3" json:"LastDeleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SessionMetadatas) Reset()         { *m = SessionMetadatas{} }
func (m *SessionMetadatas) String() string { return proto.CompactTextString(m) }
func (*SessionMetadatas) ProtoMessage()    {}
func (*SessionMetadatas) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *SessionMetadatas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionMetadatas.Unmarshal(m, b)
}
func (m *SessionMetadatas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionMetadatas.Marshal(b, m, deterministic)
}
func (m *SessionMetadatas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionMetadatas.Merge(m, src)
}
func (m *SessionMetadatas) XXX_Size() int {
	return xxx_messageInfo_SessionMetadatas.Size(m)
}
func (m *SessionMetadatas) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionMetadatas.DiscardUnknown(m)
}

var xxx_messageInfo_SessionMetadatas proto.InternalMessageInfo

func (m *SessionMetadatas) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *SessionMetadatas) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *SessionMetadatas) GetConnectedAt() int64 {
	if m != nil {
		return m.ConnectedAt
	}
	return 0
}

func (m *SessionMetadatas) GetPeer() uint64 {
	if m != nil {
		return m.Peer
	}
	return 0
}

func (m *SessionMetadatas) GetLWT() *packet.Publish {
	if m != nil {
		return m.LWT
	}
	return nil
}

func (m *SessionMetadatas) GetMountPoint() string {
	if m != nil {
		return m.MountPoint
	}
	return ""
}

func (m *SessionMetadatas) GetLastAdded() int64 {
	if m != nil {
		return m.LastAdded
	}
	return 0
}

func (m *SessionMetadatas) GetLastDeleted() int64 {
	if m != nil {
		return m.LastDeleted
	}
	return 0
}

type Subscription struct {
	SessionID            string   `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	Peer                 uint64   `protobuf:"varint,2,opt,name=Peer,proto3" json:"Peer,omitempty"`
	Pattern              []byte   `protobuf:"bytes,3,opt,name=Pattern,proto3" json:"Pattern,omitempty"`
	QoS                  int32    `protobuf:"varint,4,opt,name=QoS,proto3" json:"QoS,omitempty"`
	LastAdded            int64    `protobuf:"varint,5,opt,name=LastAdded,proto3" json:"LastAdded,omitempty"`
	LastDeleted          int64    `protobuf:"varint,6,opt,name=LastDeleted,proto3" json:"LastDeleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Subscription) Reset()         { *m = Subscription{} }
func (m *Subscription) String() string { return proto.CompactTextString(m) }
func (*Subscription) ProtoMessage()    {}
func (*Subscription) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *Subscription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subscription.Unmarshal(m, b)
}
func (m *Subscription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subscription.Marshal(b, m, deterministic)
}
func (m *Subscription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subscription.Merge(m, src)
}
func (m *Subscription) XXX_Size() int {
	return xxx_messageInfo_Subscription.Size(m)
}
func (m *Subscription) XXX_DiscardUnknown() {
	xxx_messageInfo_Subscription.DiscardUnknown(m)
}

var xxx_messageInfo_Subscription proto.InternalMessageInfo

func (m *Subscription) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *Subscription) GetPeer() uint64 {
	if m != nil {
		return m.Peer
	}
	return 0
}

func (m *Subscription) GetPattern() []byte {
	if m != nil {
		return m.Pattern
	}
	return nil
}

func (m *Subscription) GetQoS() int32 {
	if m != nil {
		return m.QoS
	}
	return 0
}

func (m *Subscription) GetLastAdded() int64 {
	if m != nil {
		return m.LastAdded
	}
	return 0
}

func (m *Subscription) GetLastDeleted() int64 {
	if m != nil {
		return m.LastDeleted
	}
	return 0
}

type SubscriptionList struct {
	Subscriptions        []*Subscription `protobuf:"bytes,1,rep,name=Subscriptions,proto3" json:"Subscriptions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SubscriptionList) Reset()         { *m = SubscriptionList{} }
func (m *SubscriptionList) String() string { return proto.CompactTextString(m) }
func (*SubscriptionList) ProtoMessage()    {}
func (*SubscriptionList) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *SubscriptionList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscriptionList.Unmarshal(m, b)
}
func (m *SubscriptionList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscriptionList.Marshal(b, m, deterministic)
}
func (m *SubscriptionList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscriptionList.Merge(m, src)
}
func (m *SubscriptionList) XXX_Size() int {
	return xxx_messageInfo_SubscriptionList.Size(m)
}
func (m *SubscriptionList) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscriptionList.DiscardUnknown(m)
}

var xxx_messageInfo_SubscriptionList proto.InternalMessageInfo

func (m *SubscriptionList) GetSubscriptions() []*Subscription {
	if m != nil {
		return m.Subscriptions
	}
	return nil
}

type StateBroadcastEvent struct {
	Subscriptions        []*Subscription     `protobuf:"bytes,1,rep,name=Subscriptions,proto3" json:"Subscriptions,omitempty"`
	SessionMetadatas     []*SessionMetadatas `protobuf:"bytes,2,rep,name=SessionMetadatas,proto3" json:"SessionMetadatas,omitempty"`
	RetainedMessages     []*RetainedMessage  `protobuf:"bytes,3,rep,name=RetainedMessages,proto3" json:"RetainedMessages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *StateBroadcastEvent) Reset()         { *m = StateBroadcastEvent{} }
func (m *StateBroadcastEvent) String() string { return proto.CompactTextString(m) }
func (*StateBroadcastEvent) ProtoMessage()    {}
func (*StateBroadcastEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *StateBroadcastEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateBroadcastEvent.Unmarshal(m, b)
}
func (m *StateBroadcastEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateBroadcastEvent.Marshal(b, m, deterministic)
}
func (m *StateBroadcastEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateBroadcastEvent.Merge(m, src)
}
func (m *StateBroadcastEvent) XXX_Size() int {
	return xxx_messageInfo_StateBroadcastEvent.Size(m)
}
func (m *StateBroadcastEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_StateBroadcastEvent.DiscardUnknown(m)
}

var xxx_messageInfo_StateBroadcastEvent proto.InternalMessageInfo

func (m *StateBroadcastEvent) GetSubscriptions() []*Subscription {
	if m != nil {
		return m.Subscriptions
	}
	return nil
}

func (m *StateBroadcastEvent) GetSessionMetadatas() []*SessionMetadatas {
	if m != nil {
		return m.SessionMetadatas
	}
	return nil
}

func (m *StateBroadcastEvent) GetRetainedMessages() []*RetainedMessage {
	if m != nil {
		return m.RetainedMessages
	}
	return nil
}

type DistributeMessageRequest struct {
	Message              *packet.Publish `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DistributeMessageRequest) Reset()         { *m = DistributeMessageRequest{} }
func (m *DistributeMessageRequest) String() string { return proto.CompactTextString(m) }
func (*DistributeMessageRequest) ProtoMessage()    {}
func (*DistributeMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *DistributeMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistributeMessageRequest.Unmarshal(m, b)
}
func (m *DistributeMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistributeMessageRequest.Marshal(b, m, deterministic)
}
func (m *DistributeMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistributeMessageRequest.Merge(m, src)
}
func (m *DistributeMessageRequest) XXX_Size() int {
	return xxx_messageInfo_DistributeMessageRequest.Size(m)
}
func (m *DistributeMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DistributeMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DistributeMessageRequest proto.InternalMessageInfo

func (m *DistributeMessageRequest) GetMessage() *packet.Publish {
	if m != nil {
		return m.Message
	}
	return nil
}

type DistributeMessageResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DistributeMessageResponse) Reset()         { *m = DistributeMessageResponse{} }
func (m *DistributeMessageResponse) String() string { return proto.CompactTextString(m) }
func (*DistributeMessageResponse) ProtoMessage()    {}
func (*DistributeMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *DistributeMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistributeMessageResponse.Unmarshal(m, b)
}
func (m *DistributeMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistributeMessageResponse.Marshal(b, m, deterministic)
}
func (m *DistributeMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistributeMessageResponse.Merge(m, src)
}
func (m *DistributeMessageResponse) XXX_Size() int {
	return xxx_messageInfo_DistributeMessageResponse.Size(m)
}
func (m *DistributeMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DistributeMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DistributeMessageResponse proto.InternalMessageInfo

type ScheduleMessageRequest struct {
	Message              *packet.Publish `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ScheduleMessageRequest) Reset()         { *m = ScheduleMessageRequest{} }
func (m *ScheduleMessageRequest) String() string { return proto.CompactTextString(m) }
func (*ScheduleMessageRequest) ProtoMessage()    {}
func (*ScheduleMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *ScheduleMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScheduleMessageRequest.Unmarshal(m, b)
}
func (m *ScheduleMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScheduleMessageRequest.Marshal(b, m, deterministic)
}
func (m *ScheduleMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduleMessageRequest.Merge(m, src)
}
func (m *ScheduleMessageRequest) XXX_Size() int {
	return xxx_messageInfo_ScheduleMessageRequest.Size(m)
}
func (m *ScheduleMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduleMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduleMessageRequest proto.InternalMessageInfo

func (m *ScheduleMessageRequest) GetMessage() *packet.Publish {
	if m != nil {
		return m.Message
	}
	return nil
}

type ScheduleMessageResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScheduleMessageResponse) Reset()         { *m = ScheduleMessageResponse{} }
func (m *ScheduleMessageResponse) String() string { return proto.CompactTextString(m) }
func (*ScheduleMessageResponse) ProtoMessage()    {}
func (*ScheduleMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *ScheduleMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScheduleMessageResponse.Unmarshal(m, b)
}
func (m *ScheduleMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScheduleMessageResponse.Marshal(b, m, deterministic)
}
func (m *ScheduleMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduleMessageResponse.Merge(m, src)
}
func (m *ScheduleMessageResponse) XXX_Size() int {
	return xxx_messageInfo_ScheduleMessageResponse.Size(m)
}
func (m *ScheduleMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduleMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduleMessageResponse proto.InternalMessageInfo

type ListSessionMetadatasRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSessionMetadatasRequest) Reset()         { *m = ListSessionMetadatasRequest{} }
func (m *ListSessionMetadatasRequest) String() string { return proto.CompactTextString(m) }
func (*ListSessionMetadatasRequest) ProtoMessage()    {}
func (*ListSessionMetadatasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *ListSessionMetadatasRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSessionMetadatasRequest.Unmarshal(m, b)
}
func (m *ListSessionMetadatasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSessionMetadatasRequest.Marshal(b, m, deterministic)
}
func (m *ListSessionMetadatasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSessionMetadatasRequest.Merge(m, src)
}
func (m *ListSessionMetadatasRequest) XXX_Size() int {
	return xxx_messageInfo_ListSessionMetadatasRequest.Size(m)
}
func (m *ListSessionMetadatasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSessionMetadatasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSessionMetadatasRequest proto.InternalMessageInfo

type ListSessionMetadatasResponse struct {
	SessionMetadatasList []*SessionMetadatas `protobuf:"bytes,1,rep,name=SessionMetadatasList,proto3" json:"SessionMetadatasList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ListSessionMetadatasResponse) Reset()         { *m = ListSessionMetadatasResponse{} }
func (m *ListSessionMetadatasResponse) String() string { return proto.CompactTextString(m) }
func (*ListSessionMetadatasResponse) ProtoMessage()    {}
func (*ListSessionMetadatasResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *ListSessionMetadatasResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSessionMetadatasResponse.Unmarshal(m, b)
}
func (m *ListSessionMetadatasResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSessionMetadatasResponse.Marshal(b, m, deterministic)
}
func (m *ListSessionMetadatasResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSessionMetadatasResponse.Merge(m, src)
}
func (m *ListSessionMetadatasResponse) XXX_Size() int {
	return xxx_messageInfo_ListSessionMetadatasResponse.Size(m)
}
func (m *ListSessionMetadatasResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSessionMetadatasResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSessionMetadatasResponse proto.InternalMessageInfo

func (m *ListSessionMetadatasResponse) GetSessionMetadatasList() []*SessionMetadatas {
	if m != nil {
		return m.SessionMetadatasList
	}
	return nil
}

type CreateSubscriptionRequest struct {
	SessionID            string   `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	Peer                 uint64   `protobuf:"varint,2,opt,name=Peer,proto3" json:"Peer,omitempty"`
	Pattern              []byte   `protobuf:"bytes,3,opt,name=Pattern,proto3" json:"Pattern,omitempty"`
	QoS                  int32    `protobuf:"varint,4,opt,name=QoS,proto3" json:"QoS,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSubscriptionRequest) Reset()         { *m = CreateSubscriptionRequest{} }
func (m *CreateSubscriptionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSubscriptionRequest) ProtoMessage()    {}
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11}
}

func (m *CreateSubscriptionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSubscriptionRequest.Unmarshal(m, b)
}
func (m *CreateSubscriptionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSubscriptionRequest.Marshal(b, m, deterministic)
}
func (m *CreateSubscriptionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSubscriptionRequest.Merge(m, src)
}
func (m *CreateSubscriptionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSubscriptionRequest.Size(m)
}
func (m *CreateSubscriptionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSubscriptionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSubscriptionRequest proto.InternalMessageInfo

func (m *CreateSubscriptionRequest) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *CreateSubscriptionRequest) GetPeer() uint64 {
	if m != nil {
		return m.Peer
	}
	return 0
}

func (m *CreateSubscriptionRequest) GetPattern() []byte {
	if m != nil {
		return m.Pattern
	}
	return nil
}

func (m *CreateSubscriptionRequest) GetQoS() int32 {
	if m != nil {
		return m.QoS
	}
	return 0
}

type CreateSubscriptionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSubscriptionResponse) Reset()         { *m = CreateSubscriptionResponse{} }
func (m *CreateSubscriptionResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSubscriptionResponse) ProtoMessage()    {}
func (*CreateSubscriptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{12}
}

func (m *CreateSubscriptionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSubscriptionResponse.Unmarshal(m, b)
}
func (m *CreateSubscriptionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSubscriptionResponse.Marshal(b, m, deterministic)
}
func (m *CreateSubscriptionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSubscriptionResponse.Merge(m, src)
}
func (m *CreateSubscriptionResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSubscriptionResponse.Size(m)
}
func (m *CreateSubscriptionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSubscriptionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSubscriptionResponse proto.InternalMessageInfo

type DeleteSubscriptionRequest struct {
	SessionID            string   `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	Peer                 uint64   `protobuf:"varint,2,opt,name=Peer,proto3" json:"Peer,omitempty"`
	Pattern              []byte   `protobuf:"bytes,3,opt,name=Pattern,proto3" json:"Pattern,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSubscriptionRequest) Reset()         { *m = DeleteSubscriptionRequest{} }
func (m *DeleteSubscriptionRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSubscriptionRequest) ProtoMessage()    {}
func (*DeleteSubscriptionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{13}
}

func (m *DeleteSubscriptionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSubscriptionRequest.Unmarshal(m, b)
}
func (m *DeleteSubscriptionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSubscriptionRequest.Marshal(b, m, deterministic)
}
func (m *DeleteSubscriptionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSubscriptionRequest.Merge(m, src)
}
func (m *DeleteSubscriptionRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSubscriptionRequest.Size(m)
}
func (m *DeleteSubscriptionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSubscriptionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSubscriptionRequest proto.InternalMessageInfo

func (m *DeleteSubscriptionRequest) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *DeleteSubscriptionRequest) GetPeer() uint64 {
	if m != nil {
		return m.Peer
	}
	return 0
}

func (m *DeleteSubscriptionRequest) GetPattern() []byte {
	if m != nil {
		return m.Pattern
	}
	return nil
}

type DeleteSubscriptionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSubscriptionResponse) Reset()         { *m = DeleteSubscriptionResponse{} }
func (m *DeleteSubscriptionResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteSubscriptionResponse) ProtoMessage()    {}
func (*DeleteSubscriptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{14}
}

func (m *DeleteSubscriptionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSubscriptionResponse.Unmarshal(m, b)
}
func (m *DeleteSubscriptionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSubscriptionResponse.Marshal(b, m, deterministic)
}
func (m *DeleteSubscriptionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSubscriptionResponse.Merge(m, src)
}
func (m *DeleteSubscriptionResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteSubscriptionResponse.Size(m)
}
func (m *DeleteSubscriptionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSubscriptionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSubscriptionResponse proto.InternalMessageInfo

type ListSubscriptionsResponse struct {
	Subscriptions        []*Subscription `protobuf:"bytes,1,rep,name=Subscriptions,proto3" json:"Subscriptions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListSubscriptionsResponse) Reset()         { *m = ListSubscriptionsResponse{} }
func (m *ListSubscriptionsResponse) String() string { return proto.CompactTextString(m) }
func (*ListSubscriptionsResponse) ProtoMessage()    {}
func (*ListSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{15}
}

func (m *ListSubscriptionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSubscriptionsResponse.Unmarshal(m, b)
}
func (m *ListSubscriptionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSubscriptionsResponse.Marshal(b, m, deterministic)
}
func (m *ListSubscriptionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSubscriptionsResponse.Merge(m, src)
}
func (m *ListSubscriptionsResponse) XXX_Size() int {
	return xxx_messageInfo_ListSubscriptionsResponse.Size(m)
}
func (m *ListSubscriptionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSubscriptionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSubscriptionsResponse proto.InternalMessageInfo

func (m *ListSubscriptionsResponse) GetSubscriptions() []*Subscription {
	if m != nil {
		return m.Subscriptions
	}
	return nil
}

type ListSubscriptionsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSubscriptionsRequest) Reset()         { *m = ListSubscriptionsRequest{} }
func (m *ListSubscriptionsRequest) String() string { return proto.CompactTextString(m) }
func (*ListSubscriptionsRequest) ProtoMessage()    {}
func (*ListSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{16}
}

func (m *ListSubscriptionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSubscriptionsRequest.Unmarshal(m, b)
}
func (m *ListSubscriptionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSubscriptionsRequest.Marshal(b, m, deterministic)
}
func (m *ListSubscriptionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSubscriptionsRequest.Merge(m, src)
}
func (m *ListSubscriptionsRequest) XXX_Size() int {
	return xxx_messageInfo_ListSubscriptionsRequest.Size(m)
}
func (m *ListSubscriptionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSubscriptionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSubscriptionsRequest proto.InternalMessageInfo

type ListRetainedMessagesRequest struct {
	Pattern              []byte   `protobuf:"bytes,1,opt,name=Pattern,proto3" json:"Pattern,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRetainedMessagesRequest) Reset()         { *m = ListRetainedMessagesRequest{} }
func (m *ListRetainedMessagesRequest) String() string { return proto.CompactTextString(m) }
func (*ListRetainedMessagesRequest) ProtoMessage()    {}
func (*ListRetainedMessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{17}
}

func (m *ListRetainedMessagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRetainedMessagesRequest.Unmarshal(m, b)
}
func (m *ListRetainedMessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRetainedMessagesRequest.Marshal(b, m, deterministic)
}
func (m *ListRetainedMessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRetainedMessagesRequest.Merge(m, src)
}
func (m *ListRetainedMessagesRequest) XXX_Size() int {
	return xxx_messageInfo_ListRetainedMessagesRequest.Size(m)
}
func (m *ListRetainedMessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRetainedMessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRetainedMessagesRequest proto.InternalMessageInfo

func (m *ListRetainedMessagesRequest) GetPattern() []byte {
	if m != nil {
		return m.Pattern
	}
	return nil
}

type ListRetainedMessagesResponse struct {
	RetainedMessages     []*RetainedMessage `protobuf:"bytes,1,rep,name=RetainedMessages,proto3" json:"RetainedMessages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ListRetainedMessagesResponse) Reset()         { *m = ListRetainedMessagesResponse{} }
func (m *ListRetainedMessagesResponse) String() string { return proto.CompactTextString(m) }
func (*ListRetainedMessagesResponse) ProtoMessage()    {}
func (*ListRetainedMessagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{18}
}

func (m *ListRetainedMessagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRetainedMessagesResponse.Unmarshal(m, b)
}
func (m *ListRetainedMessagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRetainedMessagesResponse.Marshal(b, m, deterministic)
}
func (m *ListRetainedMessagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRetainedMessagesResponse.Merge(m, src)
}
func (m *ListRetainedMessagesResponse) XXX_Size() int {
	return xxx_messageInfo_ListRetainedMessagesResponse.Size(m)
}
func (m *ListRetainedMessagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRetainedMessagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRetainedMessagesResponse proto.InternalMessageInfo

func (m *ListRetainedMessagesResponse) GetRetainedMessages() []*RetainedMessage {
	if m != nil {
		return m.RetainedMessages
	}
	return nil
}

type DeleteRetainedMessageRequest struct {
	Topic                []byte   `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRetainedMessageRequest) Reset()         { *m = DeleteRetainedMessageRequest{} }
func (m *DeleteRetainedMessageRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRetainedMessageRequest) ProtoMessage()    {}
func (*DeleteRetainedMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{19}
}

func (m *DeleteRetainedMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRetainedMessageRequest.Unmarshal(m, b)
}
func (m *DeleteRetainedMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRetainedMessageRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRetainedMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRetainedMessageRequest.Merge(m, src)
}
func (m *DeleteRetainedMessageRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRetainedMessageRequest.Size(m)
}
func (m *DeleteRetainedMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRetainedMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRetainedMessageRequest proto.InternalMessageInfo

func (m *DeleteRetainedMessageRequest) GetTopic() []byte {
	if m != nil {
		return m.Topic
	}
	return nil
}

type DeleteRetainedMessageResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRetainedMessageResponse) Reset()         { *m = DeleteRetainedMessageResponse{} }
func (m *DeleteRetainedMessageResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteRetainedMessageResponse) ProtoMessage()    {}
func (*DeleteRetainedMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{20}
}

func (m *DeleteRetainedMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRetainedMessageResponse.Unmarshal(m, b)
}
func (m *DeleteRetainedMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRetainedMessageResponse.Marshal(b, m, deterministic)
}
func (m *DeleteRetainedMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRetainedMessageResponse.Merge(m, src)
}
func (m *DeleteRetainedMessageResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteRetainedMessageResponse.Size(m)
}
func (m *DeleteRetainedMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRetainedMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRetainedMessageResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RetainedMessage)(nil), "api.RetainedMessage")
	proto.RegisterType((*SessionMetadatas)(nil), "api.SessionMetadatas")
	proto.RegisterType((*Subscription)(nil), "api.Subscription")
	proto.RegisterType((*SubscriptionList)(nil), "api.SubscriptionList")
	proto.RegisterType((*StateBroadcastEvent)(nil), "api.StateBroadcastEvent")
	proto.RegisterType((*DistributeMessageRequest)(nil), "api.DistributeMessageRequest")
	proto.RegisterType((*DistributeMessageResponse)(nil), "api.DistributeMessageResponse")
	proto.RegisterType((*ScheduleMessageRequest)(nil), "api.ScheduleMessageRequest")
	proto.RegisterType((*ScheduleMessageResponse)(nil), "api.ScheduleMessageResponse")
	proto.RegisterType((*ListSessionMetadatasRequest)(nil), "api.ListSessionMetadatasRequest")
	proto.RegisterType((*ListSessionMetadatasResponse)(nil), "api.ListSessionMetadatasResponse")
	proto.RegisterType((*CreateSubscriptionRequest)(nil), "api.CreateSubscriptionRequest")
	proto.RegisterType((*CreateSubscriptionResponse)(nil), "api.CreateSubscriptionResponse")
	proto.RegisterType((*DeleteSubscriptionRequest)(nil), "api.DeleteSubscriptionRequest")
	proto.RegisterType((*DeleteSubscriptionResponse)(nil), "api.DeleteSubscriptionResponse")
	proto.RegisterType((*ListSubscriptionsResponse)(nil), "api.ListSubscriptionsResponse")
	proto.RegisterType((*ListSubscriptionsRequest)(nil), "api.ListSubscriptionsRequest")
	proto.RegisterType((*ListRetainedMessagesRequest)(nil), "api.ListRetainedMessagesRequest")
	proto.RegisterType((*ListRetainedMessagesResponse)(nil), "api.ListRetainedMessagesResponse")
	proto.RegisterType((*DeleteRetainedMessageRequest)(nil), "api.DeleteRetainedMessageRequest")
	proto.RegisterType((*DeleteRetainedMessageResponse)(nil), "api.DeleteRetainedMessageResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 760 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xcd, 0x4e, 0xdb, 0x40,
	0x10, 0x8e, 0xf3, 0x03, 0x64, 0xa0, 0x22, 0x6c, 0x43, 0xeb, 0x98, 0x00, 0xc1, 0xa7, 0xf4, 0x40,
	0x52, 0xd1, 0x4a, 0x5c, 0x4b, 0x13, 0x0e, 0xa8, 0xa4, 0x0a, 0x4e, 0x24, 0x4e, 0x95, 0xd8, 0xd8,
	0x2b, 0x58, 0x35, 0xd8, 0x26, 0xbb, 0x41, 0xad, 0xd4, 0x6b, 0xdf, 0xa6, 0x6f, 0xd3, 0x3e, 0x50,
	0xe5, 0xdd, 0x35, 0x38, 0xf6, 0x1a, 0x54, 0x2a, 0x6e, 0xde, 0xf9, 0xf9, 0xe6, 0xef, 0x9b, 0x91,
	0xa1, 0x8a, 0x43, 0xda, 0x09, 0x67, 0x01, 0x0f, 0x50, 0x09, 0x87, 0xd4, 0x7a, 0x7b, 0x49, 0xf9,
	0xd5, 0x7c, 0xd2, 0x71, 0x83, 0xeb, 0xee, 0xed, 0xb7, 0xfd, 0x29, 0x9e, 0xb0, 0xee, 0xf5, 0x0d,
	0xe7, 0xfb, 0xc2, 0xc6, 0x0d, 0xa6, 0xdd, 0x10, 0xbb, 0x5f, 0x09, 0xef, 0x86, 0x13, 0xe9, 0x66,
	0xff, 0x80, 0x75, 0x87, 0x70, 0x4c, 0x7d, 0xe2, 0x0d, 0x08, 0x63, 0xf8, 0x92, 0xa0, 0x37, 0xb0,
	0x3c, 0x9c, 0x4f, 0xa6, 0x94, 0x5d, 0x99, 0x46, 0xcb, 0x68, 0xaf, 0x1e, 0xac, 0x77, 0xa4, 0x57,
	0x47, 0x89, 0x9d, 0x58, 0x8f, 0x9a, 0x50, 0x3d, 0xc5, 0x8c, 0x1f, 0x79, 0x1e, 0xf1, 0xcc, 0x62,
	0xcb, 0x68, 0x97, 0x9c, 0x7b, 0x01, 0x6a, 0xc1, 0x6a, 0xf4, 0xe8, 0x93, 0x29, 0xe1, 0xc4, 0x33,
	0x4b, 0x42, 0x9f, 0x14, 0xd9, 0x3f, 0x8b, 0x50, 0x1b, 0x11, 0xc6, 0x68, 0xe0, 0x0f, 0x08, 0xc7,
	0x1e, 0xe6, 0x98, 0x45, 0xa0, 0x4a, 0x76, 0xd2, 0x17, 0x19, 0x54, 0x9d, 0x7b, 0x01, 0xb2, 0x60,
	0xa5, 0x37, 0xa5, 0xc4, 0xe7, 0x27, 0x7d, 0x11, 0xb1, 0xea, 0xdc, 0xbd, 0xa3, 0x80, 0xbd, 0xc0,
	0xf7, 0x89, 0xcb, 0x89, 0x77, 0xc4, 0xe3, 0x80, 0x09, 0x11, 0x42, 0x50, 0x1e, 0x12, 0x32, 0x33,
	0xcb, 0x2d, 0xa3, 0x5d, 0x76, 0xc4, 0x37, 0xda, 0x83, 0xd2, 0xe9, 0xf9, 0xd8, 0xac, 0xe8, 0x6b,
	0x8d, 0x74, 0x68, 0x07, 0x60, 0x10, 0xcc, 0x7d, 0x3e, 0x0c, 0xa8, 0xcf, 0xcd, 0x25, 0x11, 0x36,
	0x21, 0x59, 0xec, 0xc3, 0xf2, 0x23, 0x7d, 0x58, 0xc9, 0xf6, 0xe1, 0x97, 0x01, 0x6b, 0xa3, 0xf9,
	0x84, 0xb9, 0x33, 0x1a, 0x72, 0x1a, 0xf8, 0x8f, 0xf4, 0x20, 0xae, 0xa2, 0x98, 0xa8, 0xc2, 0x84,
	0xe5, 0x21, 0xe6, 0x9c, 0xcc, 0x7c, 0x51, 0xf7, 0x9a, 0x13, 0x3f, 0x51, 0x0d, 0x4a, 0x67, 0xc1,
	0x48, 0x94, 0x5c, 0x71, 0xa2, 0xcf, 0xc5, 0x74, 0x2b, 0x8f, 0xa4, 0xbb, 0x94, 0x4d, 0xf7, 0x13,
	0xd4, 0x92, 0xd9, 0x9e, 0x52, 0xc6, 0xd1, 0x21, 0xbc, 0x48, 0xca, 0x98, 0x69, 0xb4, 0x4a, 0xed,
	0xd5, 0x83, 0x8d, 0x4e, 0x44, 0xd1, 0xa4, 0xc6, 0x59, 0xb4, 0xb3, 0x7f, 0x1b, 0xf0, 0x72, 0xc4,
	0x31, 0x27, 0x1f, 0x67, 0x01, 0xf6, 0x5c, 0xcc, 0xf8, 0xf1, 0x2d, 0xf1, 0x9f, 0x0e, 0x88, 0x8e,
	0xb2, 0x9c, 0x32, 0x8b, 0xc2, 0x77, 0x53, 0xfa, 0xa6, 0x94, 0x4e, 0x96, 0x82, 0x1f, 0xa0, 0x96,
	0xda, 0x0a, 0x66, 0x96, 0x04, 0x44, 0x5d, 0x40, 0xa4, 0x94, 0x4e, 0xc6, 0xda, 0x3e, 0x06, 0xb3,
	0x4f, 0x19, 0x9f, 0xd1, 0xc9, 0x9c, 0x93, 0xd8, 0x8c, 0xdc, 0xcc, 0x09, 0xe3, 0xd1, 0x82, 0x29,
	0x49, 0xee, 0x82, 0x29, 0xbd, 0xbd, 0x05, 0x0d, 0x0d, 0x0c, 0x0b, 0x03, 0x9f, 0x11, 0xbb, 0x07,
	0xaf, 0x46, 0xee, 0x15, 0xf1, 0xe6, 0xd3, 0xff, 0x88, 0xd0, 0x80, 0xd7, 0x19, 0x10, 0x85, 0xbf,
	0x0d, 0x5b, 0xd1, 0x68, 0x33, 0xfd, 0x92, 0x41, 0x6c, 0x0a, 0x4d, 0xbd, 0x5a, 0xba, 0xa3, 0x13,
	0xa8, 0xa7, 0x75, 0x91, 0xbd, 0x9a, 0x63, 0xce, 0x2c, 0xb4, 0x2e, 0xf6, 0x77, 0x68, 0xf4, 0x66,
	0x04, 0x73, 0xb2, 0x30, 0x77, 0x55, 0xec, 0xb3, 0xee, 0x8a, 0xdd, 0x04, 0x4b, 0x17, 0x5a, 0xb5,
	0xe8, 0x12, 0x1a, 0x72, 0x29, 0x9e, 0x39, 0xb1, 0x28, 0x0d, 0x5d, 0x20, 0x95, 0xc6, 0x18, 0x1a,
	0x62, 0x14, 0xc9, 0x3d, 0xb8, 0x9b, 0xc3, 0x93, 0x37, 0xd3, 0x02, 0x53, 0x83, 0x2a, 0x87, 0x7f,
	0x28, 0xb9, 0x91, 0xe6, 0x7d, 0x5c, 0x7a, 0xa2, 0x10, 0x63, 0xb1, 0x90, 0x0b, 0xc9, 0x9a, 0xac,
	0xa3, 0xca, 0x56, 0xb7, 0x7a, 0xc6, 0x3f, 0xad, 0xde, 0x7b, 0x68, 0xca, 0x56, 0xa5, 0x4d, 0x55,
	0x6e, 0x75, 0xa8, 0x8c, 0x83, 0x90, 0xba, 0x2a, 0x33, 0xf9, 0xb0, 0x77, 0x61, 0x3b, 0xc7, 0x4b,
	0x26, 0x76, 0xf0, 0xa7, 0x02, 0xe5, 0xc1, 0xd9, 0x78, 0x8c, 0xc6, 0xb0, 0x91, 0x69, 0x0b, 0xda,
	0x16, 0xc9, 0xe5, 0xb5, 0xcb, 0xda, 0xc9, 0x53, 0xab, 0x01, 0x16, 0xd0, 0x39, 0xa0, 0xec, 0x80,
	0x91, 0xf4, 0xcb, 0xa5, 0x98, 0xb5, 0x9b, 0xab, 0x4f, 0x02, 0x67, 0x09, 0xac, 0x80, 0x73, 0x97,
	0x4a, 0x01, 0x3f, 0xc0, 0xfc, 0x42, 0xd4, 0x87, 0xcc, 0x6d, 0x52, 0x7d, 0xc8, 0x3b, 0x7d, 0xaa,
	0x0f, 0xf9, 0x27, 0xad, 0x80, 0x3e, 0xc3, 0x7a, 0xea, 0x1e, 0xa1, 0x2d, 0xc9, 0x54, 0xed, 0xa9,
	0xb3, 0x9a, 0x7a, 0xe5, 0x1d, 0xde, 0x17, 0xa8, 0xeb, 0xae, 0x14, 0x6a, 0xdd, 0x4f, 0x44, 0x7f,
	0xdf, 0xac, 0xbd, 0x07, 0x2c, 0xd2, 0xf0, 0x69, 0x12, 0x26, 0xe0, 0x73, 0x56, 0x24, 0x01, 0x9f,
	0xb7, 0x0b, 0x76, 0x01, 0x5d, 0xc0, 0xa6, 0x96, 0x95, 0x68, 0x2f, 0x31, 0x78, 0x3d, 0xcf, 0x2d,
	0xfb, 0x21, 0x93, 0x38, 0xc2, 0x64, 0x49, 0xfc, 0x07, 0xbe, 0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff,
	0xd1, 0xb7, 0x1e, 0x08, 0x4b, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MQTTClient is the client API for MQTT service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MQTTClient interface {
	ListSubscriptions(ctx context.Context, in *ListSubscriptionsRequest, opts ...grpc.CallOption) (*ListSubscriptionsResponse, error)
	DeleteSubscription(ctx context.Context, in *DeleteSubscriptionRequest, opts ...grpc.CallOption) (*DeleteSubscriptionResponse, error)
	CreateSubscription(ctx context.Context, in *CreateSubscriptionRequest, opts ...grpc.CallOption) (*CreateSubscriptionResponse, error)
	DistributeMessage(ctx context.Context, in *DistributeMessageRequest, opts ...grpc.CallOption) (*DistributeMessageResponse, error)
	ScheduleMessage(ctx context.Context, in *ScheduleMessageRequest, opts ...grpc.CallOption) (*ScheduleMessageResponse, error)
	ListSessionMetadatas(ctx context.Context, in *ListSessionMetadatasRequest, opts ...grpc.CallOption) (*ListSessionMetadatasResponse, error)
	ListRetainedMessages(ctx context.Context, in *ListRetainedMessagesRequest, opts ...grpc.CallOption) (*ListRetainedMessagesResponse, error)
	DeleteRetainedMessage(ctx context.Context, in *DeleteRetainedMessageRequest, opts ...grpc.CallOption) (*DeleteRetainedMessageResponse, error)
}

type mQTTClient struct {
	cc *grpc.ClientConn
}

func NewMQTTClient(cc *grpc.ClientConn) MQTTClient {
	return &mQTTClient{cc}
}

func (c *mQTTClient) ListSubscriptions(ctx context.Context, in *ListSubscriptionsRequest, opts ...grpc.CallOption) (*ListSubscriptionsResponse, error) {
	out := new(ListSubscriptionsResponse)
	err := c.cc.Invoke(ctx, "/api.MQTT/ListSubscriptions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mQTTClient) DeleteSubscription(ctx context.Context, in *DeleteSubscriptionRequest, opts ...grpc.CallOption) (*DeleteSubscriptionResponse, error) {
	out := new(DeleteSubscriptionResponse)
	err := c.cc.Invoke(ctx, "/api.MQTT/DeleteSubscription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mQTTClient) CreateSubscription(ctx context.Context, in *CreateSubscriptionRequest, opts ...grpc.CallOption) (*CreateSubscriptionResponse, error) {
	out := new(CreateSubscriptionResponse)
	err := c.cc.Invoke(ctx, "/api.MQTT/CreateSubscription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mQTTClient) DistributeMessage(ctx context.Context, in *DistributeMessageRequest, opts ...grpc.CallOption) (*DistributeMessageResponse, error) {
	out := new(DistributeMessageResponse)
	err := c.cc.Invoke(ctx, "/api.MQTT/DistributeMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mQTTClient) ScheduleMessage(ctx context.Context, in *ScheduleMessageRequest, opts ...grpc.CallOption) (*ScheduleMessageResponse, error) {
	out := new(ScheduleMessageResponse)
	err := c.cc.Invoke(ctx, "/api.MQTT/ScheduleMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mQTTClient) ListSessionMetadatas(ctx context.Context, in *ListSessionMetadatasRequest, opts ...grpc.CallOption) (*ListSessionMetadatasResponse, error) {
	out := new(ListSessionMetadatasResponse)
	err := c.cc.Invoke(ctx, "/api.MQTT/ListSessionMetadatas", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mQTTClient) ListRetainedMessages(ctx context.Context, in *ListRetainedMessagesRequest, opts ...grpc.CallOption) (*ListRetainedMessagesResponse, error) {
	out := new(ListRetainedMessagesResponse)
	err := c.cc.Invoke(ctx, "/api.MQTT/ListRetainedMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mQTTClient) DeleteRetainedMessage(ctx context.Context, in *DeleteRetainedMessageRequest, opts ...grpc.CallOption) (*DeleteRetainedMessageResponse, error) {
	out := new(DeleteRetainedMessageResponse)
	err := c.cc.Invoke(ctx, "/api.MQTT/DeleteRetainedMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MQTTServer is the server API for MQTT service.
type MQTTServer interface {
	ListSubscriptions(context.Context, *ListSubscriptionsRequest) (*ListSubscriptionsResponse, error)
	DeleteSubscription(context.Context, *DeleteSubscriptionRequest) (*DeleteSubscriptionResponse, error)
	CreateSubscription(context.Context, *CreateSubscriptionRequest) (*CreateSubscriptionResponse, error)
	DistributeMessage(context.Context, *DistributeMessageRequest) (*DistributeMessageResponse, error)
	ScheduleMessage(context.Context, *ScheduleMessageRequest) (*ScheduleMessageResponse, error)
	ListSessionMetadatas(context.Context, *ListSessionMetadatasRequest) (*ListSessionMetadatasResponse, error)
	ListRetainedMessages(context.Context, *ListRetainedMessagesRequest) (*ListRetainedMessagesResponse, error)
	DeleteRetainedMessage(context.Context, *DeleteRetainedMessageRequest) (*DeleteRetainedMessageResponse, error)
}

// UnimplementedMQTTServer can be embedded to have forward compatible implementations.
type UnimplementedMQTTServer struct {
}

func (*UnimplementedMQTTServer) ListSubscriptions(ctx context.Context, req *ListSubscriptionsRequest) (*ListSubscriptionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSubscriptions not implemented")
}
func (*UnimplementedMQTTServer) DeleteSubscription(ctx context.Context, req *DeleteSubscriptionRequest) (*DeleteSubscriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSubscription not implemented")
}
func (*UnimplementedMQTTServer) CreateSubscription(ctx context.Context, req *CreateSubscriptionRequest) (*CreateSubscriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSubscription not implemented")
}
func (*UnimplementedMQTTServer) DistributeMessage(ctx context.Context, req *DistributeMessageRequest) (*DistributeMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DistributeMessage not implemented")
}
func (*UnimplementedMQTTServer) ScheduleMessage(ctx context.Context, req *ScheduleMessageRequest) (*ScheduleMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScheduleMessage not implemented")
}
func (*UnimplementedMQTTServer) ListSessionMetadatas(ctx context.Context, req *ListSessionMetadatasRequest) (*ListSessionMetadatasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSessionMetadatas not implemented")
}
func (*UnimplementedMQTTServer) ListRetainedMessages(ctx context.Context, req *ListRetainedMessagesRequest) (*ListRetainedMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRetainedMessages not implemented")
}
func (*UnimplementedMQTTServer) DeleteRetainedMessage(ctx context.Context, req *DeleteRetainedMessageRequest) (*DeleteRetainedMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRetainedMessage not implemented")
}

func RegisterMQTTServer(s *grpc.Server, srv MQTTServer) {
	s.RegisterService(&_MQTT_serviceDesc, srv)
}

func _MQTT_ListSubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSubscriptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MQTTServer).ListSubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MQTT/ListSubscriptions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MQTTServer).ListSubscriptions(ctx, req.(*ListSubscriptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MQTT_DeleteSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MQTTServer).DeleteSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MQTT/DeleteSubscription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MQTTServer).DeleteSubscription(ctx, req.(*DeleteSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MQTT_CreateSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MQTTServer).CreateSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MQTT/CreateSubscription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MQTTServer).CreateSubscription(ctx, req.(*CreateSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MQTT_DistributeMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DistributeMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MQTTServer).DistributeMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MQTT/DistributeMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MQTTServer).DistributeMessage(ctx, req.(*DistributeMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MQTT_ScheduleMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MQTTServer).ScheduleMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MQTT/ScheduleMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MQTTServer).ScheduleMessage(ctx, req.(*ScheduleMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MQTT_ListSessionMetadatas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionMetadatasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MQTTServer).ListSessionMetadatas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MQTT/ListSessionMetadatas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MQTTServer).ListSessionMetadatas(ctx, req.(*ListSessionMetadatasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MQTT_ListRetainedMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRetainedMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MQTTServer).ListRetainedMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MQTT/ListRetainedMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MQTTServer).ListRetainedMessages(ctx, req.(*ListRetainedMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MQTT_DeleteRetainedMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRetainedMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MQTTServer).DeleteRetainedMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MQTT/DeleteRetainedMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MQTTServer).DeleteRetainedMessage(ctx, req.(*DeleteRetainedMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MQTT_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.MQTT",
	HandlerType: (*MQTTServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSubscriptions",
			Handler:    _MQTT_ListSubscriptions_Handler,
		},
		{
			MethodName: "DeleteSubscription",
			Handler:    _MQTT_DeleteSubscription_Handler,
		},
		{
			MethodName: "CreateSubscription",
			Handler:    _MQTT_CreateSubscription_Handler,
		},
		{
			MethodName: "DistributeMessage",
			Handler:    _MQTT_DistributeMessage_Handler,
		},
		{
			MethodName: "ScheduleMessage",
			Handler:    _MQTT_ScheduleMessage_Handler,
		},
		{
			MethodName: "ListSessionMetadatas",
			Handler:    _MQTT_ListSessionMetadatas_Handler,
		},
		{
			MethodName: "ListRetainedMessages",
			Handler:    _MQTT_ListRetainedMessages_Handler,
		},
		{
			MethodName: "DeleteRetainedMessage",
			Handler:    _MQTT_DeleteRetainedMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
