// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package auth

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransportContext struct {
	Encrypted            bool     `protobuf:"varint,1,opt,name=Encrypted,proto3" json:"Encrypted,omitempty"`
	RemoteAddress        string   `protobuf:"bytes,2,opt,name=RemoteAddress,proto3" json:"RemoteAddress,omitempty"`
	X509Certificate      []byte   `protobuf:"bytes,3,opt,name=X509Certificate,proto3" json:"X509Certificate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransportContext) Reset()         { *m = TransportContext{} }
func (m *TransportContext) String() string { return proto.CompactTextString(m) }
func (*TransportContext) ProtoMessage()    {}
func (*TransportContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *TransportContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransportContext.Unmarshal(m, b)
}
func (m *TransportContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransportContext.Marshal(b, m, deterministic)
}
func (m *TransportContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransportContext.Merge(m, src)
}
func (m *TransportContext) XXX_Size() int {
	return xxx_messageInfo_TransportContext.Size(m)
}
func (m *TransportContext) XXX_DiscardUnknown() {
	xxx_messageInfo_TransportContext.DiscardUnknown(m)
}

var xxx_messageInfo_TransportContext proto.InternalMessageInfo

func (m *TransportContext) GetEncrypted() bool {
	if m != nil {
		return m.Encrypted
	}
	return false
}

func (m *TransportContext) GetRemoteAddress() string {
	if m != nil {
		return m.RemoteAddress
	}
	return ""
}

func (m *TransportContext) GetX509Certificate() []byte {
	if m != nil {
		return m.X509Certificate
	}
	return nil
}

type ApplicationContext struct {
	Username             []byte   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             []byte   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	ClientID             []byte   `protobuf:"bytes,3,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplicationContext) Reset()         { *m = ApplicationContext{} }
func (m *ApplicationContext) String() string { return proto.CompactTextString(m) }
func (*ApplicationContext) ProtoMessage()    {}
func (*ApplicationContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *ApplicationContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationContext.Unmarshal(m, b)
}
func (m *ApplicationContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationContext.Marshal(b, m, deterministic)
}
func (m *ApplicationContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationContext.Merge(m, src)
}
func (m *ApplicationContext) XXX_Size() int {
	return xxx_messageInfo_ApplicationContext.Size(m)
}
func (m *ApplicationContext) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationContext.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationContext proto.InternalMessageInfo

func (m *ApplicationContext) GetUsername() []byte {
	if m != nil {
		return m.Username
	}
	return nil
}

func (m *ApplicationContext) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

func (m *ApplicationContext) GetClientID() []byte {
	if m != nil {
		return m.ClientID
	}
	return nil
}

type WaspAuthenticationRequest struct {
	MQTT                 *ApplicationContext `protobuf:"bytes,1,opt,name=MQTT,proto3" json:"MQTT,omitempty"`
	Transport            *TransportContext   `protobuf:"bytes,2,opt,name=Transport,proto3" json:"Transport,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *WaspAuthenticationRequest) Reset()         { *m = WaspAuthenticationRequest{} }
func (m *WaspAuthenticationRequest) String() string { return proto.CompactTextString(m) }
func (*WaspAuthenticationRequest) ProtoMessage()    {}
func (*WaspAuthenticationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *WaspAuthenticationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WaspAuthenticationRequest.Unmarshal(m, b)
}
func (m *WaspAuthenticationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WaspAuthenticationRequest.Marshal(b, m, deterministic)
}
func (m *WaspAuthenticationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WaspAuthenticationRequest.Merge(m, src)
}
func (m *WaspAuthenticationRequest) XXX_Size() int {
	return xxx_messageInfo_WaspAuthenticationRequest.Size(m)
}
func (m *WaspAuthenticationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WaspAuthenticationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WaspAuthenticationRequest proto.InternalMessageInfo

func (m *WaspAuthenticationRequest) GetMQTT() *ApplicationContext {
	if m != nil {
		return m.MQTT
	}
	return nil
}

func (m *WaspAuthenticationRequest) GetTransport() *TransportContext {
	if m != nil {
		return m.Transport
	}
	return nil
}

type WaspAuthenticationResponse struct {
	MountPoint           []byte   `protobuf:"bytes,1,opt,name=MountPoint,proto3" json:"MountPoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WaspAuthenticationResponse) Reset()         { *m = WaspAuthenticationResponse{} }
func (m *WaspAuthenticationResponse) String() string { return proto.CompactTextString(m) }
func (*WaspAuthenticationResponse) ProtoMessage()    {}
func (*WaspAuthenticationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *WaspAuthenticationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WaspAuthenticationResponse.Unmarshal(m, b)
}
func (m *WaspAuthenticationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WaspAuthenticationResponse.Marshal(b, m, deterministic)
}
func (m *WaspAuthenticationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WaspAuthenticationResponse.Merge(m, src)
}
func (m *WaspAuthenticationResponse) XXX_Size() int {
	return xxx_messageInfo_WaspAuthenticationResponse.Size(m)
}
func (m *WaspAuthenticationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WaspAuthenticationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WaspAuthenticationResponse proto.InternalMessageInfo

func (m *WaspAuthenticationResponse) GetMountPoint() []byte {
	if m != nil {
		return m.MountPoint
	}
	return nil
}

func init() {
	proto.RegisterType((*TransportContext)(nil), "auth.TransportContext")
	proto.RegisterType((*ApplicationContext)(nil), "auth.ApplicationContext")
	proto.RegisterType((*WaspAuthenticationRequest)(nil), "auth.WaspAuthenticationRequest")
	proto.RegisterType((*WaspAuthenticationResponse)(nil), "auth.WaspAuthenticationResponse")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcd, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x8d, 0x16, 0x69, 0xa7, 0xf5, 0x83, 0x3d, 0x94, 0x58, 0x44, 0x43, 0xf0, 0x90, 0x83,
	0x14, 0xa9, 0x7a, 0x10, 0xbc, 0x94, 0xea, 0xc1, 0x43, 0xa1, 0x2e, 0x15, 0xbd, 0x78, 0x58, 0x9b,
	0x91, 0x04, 0xda, 0xdd, 0x75, 0x77, 0x82, 0x7a, 0xd2, 0x3f, 0x5d, 0xb2, 0x89, 0xe9, 0x87, 0xf6,
	0xb6, 0xef, 0xcd, 0x0c, 0xef, 0x37, 0xc3, 0x02, 0x88, 0x8c, 0x92, 0xae, 0x36, 0x8a, 0x14, 0xab,
	0xe5, 0xef, 0xf0, 0xdb, 0x83, 0xfd, 0xb1, 0x11, 0xd2, 0x6a, 0x65, 0x68, 0xa0, 0x24, 0xe1, 0x07,
	0xb1, 0x43, 0x68, 0xdc, 0xca, 0x89, 0xf9, 0xd4, 0x84, 0xb1, 0xef, 0x05, 0x5e, 0x54, 0xe7, 0x73,
	0x83, 0x9d, 0xc0, 0x0e, 0xc7, 0x99, 0x22, 0xec, 0xc7, 0xb1, 0x41, 0x6b, 0xfd, 0xcd, 0xc0, 0x8b,
	0x1a, 0x7c, 0xd9, 0x64, 0x11, 0xec, 0x3d, 0x5d, 0x9e, 0x5d, 0x0d, 0xd0, 0x50, 0xfa, 0x9a, 0x4e,
	0x04, 0xa1, 0xbf, 0x15, 0x78, 0x51, 0x8b, 0xaf, 0xda, 0x61, 0x02, 0xac, 0xaf, 0xf5, 0x34, 0x17,
	0xa9, 0x92, 0xbf, 0x0c, 0x1d, 0xa8, 0x3f, 0x58, 0x34, 0x52, 0xcc, 0xd0, 0x21, 0xb4, 0x78, 0xa5,
	0xf3, 0xda, 0x48, 0x58, 0xfb, 0xae, 0x4c, 0xec, 0xc2, 0x5b, 0xbc, 0xd2, 0x79, 0x6d, 0x30, 0x4d,
	0x51, 0xd2, 0xdd, 0x4d, 0x19, 0x58, 0xe9, 0xf0, 0x0b, 0x0e, 0x1e, 0x85, 0xd5, 0xfd, 0x8c, 0x12,
	0x94, 0x54, 0x06, 0x72, 0x7c, 0xcb, 0xd0, 0x12, 0x3b, 0x85, 0xda, 0xf0, 0x7e, 0x3c, 0x76, 0x61,
	0xcd, 0x9e, 0xdf, 0x75, 0xa7, 0xfa, 0x0b, 0xc6, 0x5d, 0x17, 0xbb, 0x80, 0x46, 0x75, 0x36, 0xc7,
	0xd0, 0xec, 0xb5, 0x8b, 0x91, 0xd5, 0x6b, 0xf2, 0x79, 0x63, 0x78, 0x0d, 0x9d, 0xff, 0x00, 0xac,
	0x56, 0xd2, 0x22, 0x3b, 0x02, 0x18, 0xaa, 0x4c, 0xd2, 0x48, 0xa5, 0x92, 0xca, 0xa5, 0x17, 0x9c,
	0x9e, 0x82, 0xdd, 0xe5, 0x49, 0xf6, 0x0c, 0xed, 0x05, 0x07, 0x73, 0xb2, 0x62, 0x59, 0x76, 0x5c,
	0xc0, 0xac, 0x5d, 0xb7, 0x13, 0xac, 0x6f, 0x28, 0x70, 0xc2, 0x8d, 0x97, 0x6d, 0xf7, 0x53, 0xce,
	0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x83, 0x3a, 0x96, 0x47, 0x37, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthenticationClient is the client API for Authentication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthenticationClient interface {
	AuthenticateMQTTClient(ctx context.Context, in *WaspAuthenticationRequest, opts ...grpc.CallOption) (*WaspAuthenticationResponse, error)
}

type authenticationClient struct {
	cc *grpc.ClientConn
}

func NewAuthenticationClient(cc *grpc.ClientConn) AuthenticationClient {
	return &authenticationClient{cc}
}

func (c *authenticationClient) AuthenticateMQTTClient(ctx context.Context, in *WaspAuthenticationRequest, opts ...grpc.CallOption) (*WaspAuthenticationResponse, error) {
	out := new(WaspAuthenticationResponse)
	err := c.cc.Invoke(ctx, "/auth.Authentication/AuthenticateMQTTClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticationServer is the server API for Authentication service.
type AuthenticationServer interface {
	AuthenticateMQTTClient(context.Context, *WaspAuthenticationRequest) (*WaspAuthenticationResponse, error)
}

// UnimplementedAuthenticationServer can be embedded to have forward compatible implementations.
type UnimplementedAuthenticationServer struct {
}

func (*UnimplementedAuthenticationServer) AuthenticateMQTTClient(ctx context.Context, req *WaspAuthenticationRequest) (*WaspAuthenticationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthenticateMQTTClient not implemented")
}

func RegisterAuthenticationServer(s *grpc.Server, srv AuthenticationServer) {
	s.RegisterService(&_Authentication_serviceDesc, srv)
}

func _Authentication_AuthenticateMQTTClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaspAuthenticationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServer).AuthenticateMQTTClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Authentication/AuthenticateMQTTClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServer).AuthenticateMQTTClient(ctx, req.(*WaspAuthenticationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Authentication_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.Authentication",
	HandlerType: (*AuthenticationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthenticateMQTTClient",
			Handler:    _Authentication_AuthenticateMQTTClient_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
